CREATE SEQUENCE FLIGHT_SEQ INCREMENT BY 1 MAXVALUE 1000 CYCLE;
DROP SEQUENCE FLIGHT_SEQ;

CREATE SEQUENCE PASSENGER_SEQ INCREMENT BY 1 MAXVALUE 1000 CYCLE;
DROP SEQUENCE PASSENGER_SEQ;

CREATE SEQUENCE PLANE_SEQ INCREMENT BY 1 MAXVALUE 1000 CYCLE;
DROP SEQUENCE PLANE_SEQ;


--Plane:
--Long id
--String model
--String code
--Date yearProduced
--Double avgFuelConsumption

CREATE TABLE PLANE(
ID NUMBER PRIMARY KEY,
MODEL NVARCHAR2(50) NOT NULL,
CODE NVARCHAR2(50) NOT NULL,
YEAR_PRODUCED DATE NOT NULL,
AVG_FUEL_CONSUMPTION NUMBER (5,2)
);

--Flight:
--Long id
--Plane plane
--Collection passenger
--Date dateFlight
--String cityFrom
--String cityTo

CREATE TABLE FLIGHT(
ID NUMBER PRIMARY KEY,
PLANE NUMBER,
CONSTRAINT PLANE_FK FOREIGN KEY (PLANE) REFERENCES PLANE(ID),
DATE_FLIGHT DATE NOT NULL,
CITY_FROM NVARCHAR2(50) NOT NULL,
CITY_TO NVARCHAR2(50) NOT NULL
);
--DELETE SET ON

--Passenger:
--Long id
--String lastName
--String nationality
--Date dateOfBirth
--String passportCode
--Collection flights

CREATE TABLE PASSENGERS(
ID NUMBER PRIMARY KEY,
LAST_NAME NVARCHAR2(50) NOT NULL,
NATIONALITY NVARCHAR2(50) NOT NULL,
DATE_OF_BIRTH DATE NOT NULL,
PASSPORT_CODE NVARCHAR2(50) NOT NULL,
FLIGHT NUMBER,
CONSTRAINT FLIGHT_FK FOREIGN KEY (FLIGHT) REFERENCES FLIGHT(ID)
);

CREATE TABLE FLIGHTS_PASSENGERS(
FLIGHT_ID NUMBER,
CONSTRAINT FLIGHTS_FK FOREIGN KEY (FLIGHT_ID) REFERENCES FLIGHT(ID),
PASSENGER_ID NUMBER,
CONSTRAINT PASSENGERS_FK FOREIGN KEY (PASSENGER_ID) REFERENCES PASSENGER(ID)
);