CREATE SEQUENCE FLIGHT_SEQ INCREMENT BY 1 MAXVALUE 1000 CYCLE;
DROP SEQUENCE FLIGHT_SEQ;

CREATE SEQUENCE PASSENGER_SEQ INCREMENT BY 1 MAXVALUE 1000 CYCLE;
DROP SEQUENCE PASSENGER_SEQ;

CREATE SEQUENCE PLANE_SEQ INCREMENT BY 1 MAXVALUE 1000 CYCLE;
DROP SEQUENCE PLANE_SEQ;